### ISSUE TITLE
Fails to run on Mobile Safari under Cordova

### ISSUE THREAD

**Issue by cfjedimaster** [sbisbee/sag-js#30]
I get a "whoops" error when running in a Cordova app. It appears to be this block:

    if(typeof XMLHttpRequest === 'function') {
    xmlHTTP = new XMLHttpRequest();
    }
    else if(typeof ActiveXObject === 'function') {
   xmlHTTP = new ActiveXObject('Microsoft.XMLHTTP');
    }
    else if(typeof require === 'function') {
      http = (useSSL) ? require('https') : require('http');
     urlUtils = require('url');
    }
    else {
      throw new Error('whoops');
    }

Going into my console, typeof is returning object, not function.

**Comment by sbisbee** [comment]
Apologies, I didn't realize people were still filing issues to this repo. I've posted a note that I haven't been maintaining this project for years. Closing ticket.
